services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-test-app
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    environment:
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_PORT=3301
    networks:
      - app-network

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool-test
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool/app:/opt/tarantool/app
      - ./tarantool/data:/var/lib/tarantool
      - /tmp/tarantool/run:/var/run/tarantool
      - ./tarantool/logs:/var/log/tarantool
    environment:
      - TT_APP_NAME=app
      - TT_INSTANCE_NAME=instance001
      - TT_PASS=${TRNTLPASS}
    command: tarantool
    restart: unless-stopped
    privileged: true
    networks:
      - app-network


networks:
  app-network:
    driver: bridge